// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr80r1w1Ns_H6iKOfFPEdBkEtIxmgkarU',
    appId: '1:531196138685:web:53a485f314869ee04813d4',
    messagingSenderId: '531196138685',
    projectId: 'bus-ticket-issuing-system',
    authDomain: 'bus-ticket-issuing-system.firebaseapp.com',
    storageBucket: 'bus-ticket-issuing-system.firebasestorage.app',
    measurementId: 'G-CL56ECKB7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHEvvXI6wwNbw_8bV6_8AHkRaC7nlzGOA',
    appId: '1:531196138685:android:1d08682124cff6d74813d4',
    messagingSenderId: '531196138685',
    projectId: 'bus-ticket-issuing-system',
    storageBucket: 'bus-ticket-issuing-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Q1SOlmpm40fJ1LgV_i5iq2Qsyg4VGpo',
    appId: '1:531196138685:ios:8631409743492f514813d4',
    messagingSenderId: '531196138685',
    projectId: 'bus-ticket-issuing-system',
    storageBucket: 'bus-ticket-issuing-system.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Q1SOlmpm40fJ1LgV_i5iq2Qsyg4VGpo',
    appId: '1:531196138685:ios:8631409743492f514813d4',
    messagingSenderId: '531196138685',
    projectId: 'bus-ticket-issuing-system',
    storageBucket: 'bus-ticket-issuing-system.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr80r1w1Ns_H6iKOfFPEdBkEtIxmgkarU',
    appId: '1:531196138685:web:9737c8b3ae5eb91e4813d4',
    messagingSenderId: '531196138685',
    projectId: 'bus-ticket-issuing-system',
    authDomain: 'bus-ticket-issuing-system.firebaseapp.com',
    storageBucket: 'bus-ticket-issuing-system.firebasestorage.app',
    measurementId: 'G-44QWB00F0J',
  );
}
